alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
functions:
- github:
    branch: main
    deploy_on_push: true
    repo: yayforms/count-token
  name: emails-api
  routes:
  - path: /
  source_dir: /
name: emails